---
title: "Scottish 2.0"
author: '- BB; KS -'
date: "July 17, 2017"
output: html_document
---

```{r setup, include=FALSE}
library(rmarkdown)
library(knitr)
```

# Finding Schemes

We need to figure out exactly what we want to store in each table.

## Recipe
```{r Recipe, echo= FALSE}
recipe <- data.frame(
  Recipe = "Recipe1",
  Style = "Scottish Ale 70 Shilling",
  Date = Sys.Date(),
  OG = 1.050,
  FG = 1.010 
)

kable(recipe)
```

## Fermentables
```{r Fermentables, echo= FALSE}
fermentables <- data.frame(
  Recipe = rep("Recipe1",5),
  Ingredients = c("2-Row","2-Row","2-Row","2-Row","2-Row"),
  Lbs = c(8,2.5,1,0.5,0.5)
)

kable(fermentables)
```

## Hops
```{r Hops, echo= FALSE}
hops <- data.frame(
  Recipe = rep("Recipe1",5),
  Hop = c("Admiral","Admiral","Admiral","Admiral","Admiral"),
  Weight = c(1,1,0,0,0),
  Boil_Time = c(60,30,0,0,0),
  IBU = c(50,20,5,0,0)
)

kable(hops)
```

## Mash
```{r Mash, echo= FALSE}
mash <- data.frame(
  Recipe = "Recipe1",
  Mash_Thickness = 1.25,
  Sacc_Rest = 150,
  Infusion_Temp = 167,
  Mash_Vol = 4,
  Sparge_Vol = 4
)

kable(mash)
```

## Yeast
```{r Yeast, echo= FALSE}
yeast <- data.frame(
  Recipe = "Recipe1",
  Yeast_Strain = "Brewferm Lager Yeast",
  Attenuation = 0,
  Initial_Cell_Count_Billions = 150,
  Pitched_Cells_Billions = 150,
  Liters_For_Starter = 0,
  Time_For_Starter = 0
)

kable(yeast)
```

## Fermentation
```{r Fermentation, echo= FALSE}
fermentation <- data.frame(
  Recipe = "Recipe1",
  Temp1 = 70,
  Days1 = 7,
  Temp2 = 70,
  Days2 = 7,
  Temp3 = 70,
  Days3 = 7,
  Temp4 = 70,
  Days4 = 7,
  Temp5 = 70,
  Days5 = 7
)

kable(fermentation)
```